### ISSUE TITLE
[PANIC] >= 1.3.4-beta7

### ISSUE THREAD

**Issue by VillanCh** [yaklang/syntaxflow-zero-to-hero#8]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x101bdad7b]

goroutine 21642 [running]:
github.com/yaklang/yaklang/common/yak/ssa.(*Parameter).SetDefault(...)
 /Users/runner/work/yaklang/yaklang/common/yak/ssa/ssa.go:517
github.com/yaklang/yaklang/common/yak/ssa.unmarshalExtraInformation({0x1044f5a80?, 0xc0160eb1d0?}, 0xc0160eb1d0?)
 /Users/runner/work/yaklang/yaklang/common/yak/ssa/database_marshal.go:446 +0xcfb
github.com/yaklang/yaklang/common/yak/ssa.(*Cache).IrCodeToInstruction(0xc0b0ace480?, {0x1044f5a80, 0xc0160eb1d0}, 0x1162005b8?)
 /Users/runner/work/yaklang/yaklang/common/yak/ssa/database_code.go:31 +0x65
github.com/yaklang/yaklang/common/yak/ssa.(*LazyInstruction).check(0xc0b0ace480)
 /Users/runner/work/yaklang/yaklang/common/yak/ssa/instructionLazy.go:129 +0xc5
github.com/yaklang/yaklang/common/yak/ssa.(*LazyInstruction).IsAnnotation(0xc0b0ace480)
 /Users/runner/work/yaklang/yaklang/common/yak/ssa/instructionLazy.go:308 +0x1e
github.com/yaklang/yaklang/common/yak/ssa/ssadb.SaveVariable(0x15303fdd4d3fc?, {0x30cceeb55, 0x4}, {0xc0b3dde248, 0x1}, {0xc0aa265e60, 0x11, 0x6687c1cc?})
 /Users/runner/work/yaklang/yaklang/common/yak/ssa/ssadb/variable.go:54 +0x262
github.com/yaklang/yaklang/common/yak/ssa.(*Cache).saveVariable(0xc007342940, {0xc0b3dde248, 0x1}, {0xc000229cc0?, 0x222d3984f8?, 0x106fc9d60?})
 /Users/runner/work/yaklang/yaklang/common/yak/ssa/database_cache.go:240 +0x8f
github.com/yaklang/yaklang/common/yak/ssa.NewDBCache.func2({0xc0b3dde248?, 0xc00aa027b0?}, {0xc000229cc0?, 0x24?, 0x102d5fe20?})
 /Users/runner/work/yaklang/yaklang/common/yak/ssa/database_cache.go:73 +0x39
github.com/yaklang/yaklang/common/utils.(*CacheWithKey[...]).clearExpireItem(0x104544400)
 /Users/runner/work/yaklang/yaklang/common/utils/cache.go:178 +0x146
github.com/yaklang/yaklang/common/utils.(*CacheWithKey[...]).startExpirationProcessing(0x104544400)
 /Users/runner/work/yaklang/yaklang/common/utils/cache.go:235 +0x65
created by github.com/yaklang/yaklang/common/utils.NewTTLCacheWithKey[...]
 /Users/runner/work/yaklang/yaklang/common/utils/cache.go:419 +0x1d8
```

**Comment by littlepillow007** [comment]
修复:https://github.com/yaklang/yaklang/pull/1547
